abstract: APML parser/builder
author: Lyo Kato, C<lyo.kato at gmail.com>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: XML-APML
no_index: 
  directory: 
    - inc
    - t
requires: 
  Class::Accessor: 0.31
  Class::Data::Accessor: 0.04001
  XML::LibXML: 1.65
  perl: 5.8.1
version: 0.02
